name: Daily Economy Report

on:
  schedule:
    - cron: '30 21 * * *' # KST 06:30
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v3 -> v4로 업데이트
      - name: Set up Python
        uses: actions/setup-python@v5 # v4 -> v5로 업데이트
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install yfinance python-telegram-bot
      - name: Run script
        run: python economy_bot.py
